In [22]:
import pandas as pd
import numpy as np

In [23]:
df = pd.read_csv('customer.csv')

In [24]:
df

,age,gender,review,education,purchased
0,30,Female,Average,School,No
1,68,Female,Poor,UG,No
2,70,Female,Good,PG,No
3,72,Female,Good,PG,No
4,16,Female,Average,UG,No
5,31,Female,Average,School,Yes
6,18,Male,Good,School,No
7,60,Female,Poor,School,Yes
8,65,Female,Average,UG,No
9,74,Male,Good,UG,Yes


In [25]:
df.head()

,age,gender,review,education,purchased
0,30,Female,Average,School,No
1,68,Female,Poor,UG,No
2,70,Female,Good,PG,No
3,72,Female,Good,PG,No
4,16,Female,Average,UG,No


In [26]:
df.describe()

,age
count,50.000000
mean,54.160000
std,25.658161
min,15.000000
25%,30.250000
50%,57.000000
75%,74.000000
max,98.000000


In [27]:
df.shape

(50, 5)

In [28]:
df.isnull().sum()

age          0
gender       0
review       0
education    0
purchased    0
dtype: int64

In [29]:
df.count()

age          50
gender       50
review       50
education    50
purchased    50
dtype: int64

In [30]:
df.std

<bound method DataFrame.std of     age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average

In [31]:
df.sum()

age                                                       2708
gender       FemaleFemaleFemaleFemaleFemaleFemaleMaleFemale...
review       AveragePoorGoodGoodAverageAverageGoodPoorAvera...
education    SchoolUGPGPGUGSchoolSchoolSchoolUGUGUGUGSchool...
purchased    NoNoNoNoNoYesNoYesNoYesYesYesNoNoYesNoYesYesNo...
dtype: object

In [32]:
df.mean

<bound method DataFrame.mean of     age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Averag

In [33]:
df.min()

age               15
gender        Female
review       Average
education         PG
purchased         No
dtype: object

In [34]:
df.sample(3)

,age,gender,review,education,purchased
20,57,Female,Average,School,Yes
27,69,Female,Poor,PG,No
43,27,Male,Poor,PG,No


as we can see in this data there is first col which is 
age = numeric data 
gender = n0minal categorical data --->>> one hot encoding
review= ordinal categorical data ---->>> ordinal encoding
education = ordinal categorical data --->>> ordinal encoding
purchased = categorical --->>>>>>> label encoding

In [36]:
df = df.iloc[ : , 2 : ]

In [37]:
df

,review,education,purchased
0,Average,School,No
1,Poor,UG,No
2,Good,PG,No
3,Good,PG,No
4,Average,UG,No
5,Average,School,Yes
6,Good,School,No
7,Poor,School,Yes
8,Average,UG,No
9,Good,UG,Yes


In [40]:
df.sample(7)

,review,education,purchased
43,Poor,PG,No
42,Good,PG,Yes
17,Poor,UG,Yes
27,Poor,PG,No
45,Poor,PG,Yes
30,Average,UG,No
8,Average,UG,No


In [80]:
df.head(37)

,review,education,purchased
0,Average,School,No
1,Poor,UG,No
2,Good,PG,No
3,Good,PG,No
4,Average,UG,No
5,Average,School,Yes
6,Good,School,No
7,Poor,School,Yes
8,Average,UG,No
9,Good,UG,Yes


In [44]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1],test_size=0.2)

In [46]:
x_train

,review,education
36,Good,UG
19,Poor,PG
44,Average,UG
41,Good,PG
15,Poor,UG
42,Good,PG
4,Average,UG
14,Poor,PG
47,Good,PG
39,Poor,PG


In [47]:
y_train

36    Yes
19    Yes
44     No
41    Yes
15     No
42    Yes
4      No
14    Yes
47    Yes
39     No
20    Yes
35    Yes
27     No
2      No
40     No
11    Yes
38     No
49     No
23     No
8      No
16    Yes
1      No
0      No
9     Yes
31    Yes
17    Yes
13     No
24    Yes
22    Yes
34     No
48    Yes
30     No
28     No
43     No
45    Yes
5     Yes
37    Yes
21     No
12     No
7     Yes
Name: purchased, dtype: object

In [49]:
from sklearn.preprocessing import OrdinalEncoder

In [50]:
ord_encoder = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [51]:
ord_encoder

,categories,"[['Poor', 'Average', ...], ['School', 'UG', ...]]"
,dtype,<class 'numpy.float64'>
,handle_unknown,'error'
,unknown_value,None
,encoded_missing_value,nan
,min_frequency,None
,max_categories,None


In [52]:
ord_encoder.fit(x_train)

,categories,"[['Poor', 'Average', ...], ['School', 'UG', ...]]"
,dtype,<class 'numpy.float64'>
,handle_unknown,'error'
,unknown_value,None
,encoded_missing_value,nan
,min_frequency,None
,max_categories,None


In [53]:
x_train = ord_encoder.transform(x_train)
x_test = ord_encoder.transform(x_test)

In [54]:
x_train

array([[2., 1.],
       [0., 2.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [0., 2.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [2., 1.],
       [2., 0.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [2., 1.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 2.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [1., 2.],
       [1., 2.],
       [0., 0.],
       [0., 0.]])

In [55]:
ord_encoder.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

# applying the label encoding on output column 
first of all must rememeber that we always apply the label encoding on the output coumn only 

In [72]:
from sklearn.preprocessing import LabelEncoder

In [73]:
label_encoder = LabelEncoder()

In [74]:
label_encoder

LabelEncoder()

In [75]:
label_encoder.fit(y_train)

LabelEncoder()

In [76]:
label_encoder.classes_

array([0, 1])

In [77]:
y_train = label_encoder.transform(y_train)
y_test = label_encoder.transform(y_test)

In [78]:
y_train

array([1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1])