In [1]:
import numpy as np

In [2]:
x = np.array(6)

In [3]:
x

array(6)

In [4]:
x.ndim

0

In [5]:
x = np.array([1,2,3,4])

In [6]:
x

array([1, 2, 3, 4])

In [7]:
x.ndim

1

In [11]:
x = np.array([[1,2],[3,4]])

In [12]:
x

array([[1, 2],
       [3, 4]])

In [13]:
x.ndim

2

In [18]:
x.shape

(2, 2)

In [20]:
a = np.array([[1,2,3],[4,5,6]])

In [21]:
b = np.array([[5,6,2],[7,8,9]])

In [22]:
print("addition = ", a + b)

addition [[ 6  8  5]
 [11 13 15]]
